### ISSUE TITLE
Create quarkus example project

### ISSUE THREAD

**Issue by miyasama** [dbflute-example/dbflute-example-on-quarkus#10]
@jflute 
QuarkusのExampleの作成についてですが、以下の４つのPRで実装を行いました。
※上から多段PRになっています。

---
1. マルチプロジェクト構成への変更（QuarkusでDBFluteを使うために必要だった）
https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/6

2. 単純にrenewalタスク実行
https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/7

3. DBFluteをQuarkusで使用できるようにするための設定
https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/8

4. 簡単なサンプル実装を追加
https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/9
---

最後のPRのブランチ `feature/example-application` が、一旦の完成版です。
READMEに、QuarkusでDBFluteを使うために必要な事項を記載しています。

exampleとしては最低限の実装となっていまして、APIを適当なもの１つしか作っていません。
https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/9/files#diff-f43596ad7b48a9278c8ab5df0eec5e7332631f11ff1965efb8ae3d99d7c34f10R12-R24

どの程度まで作るべきかや、PRの作り方など、作法などあればご教授いただきたく 🙏 
一度内容を確認お願いできると嬉しいです。

**Comment by jflute** [comment]
@miyasama おおぉー、すごい、ありがとうー！

4つのプルリクマージする時は4-3-2-1の順番でいいのかな？
Exampleとしての体裁的なところは自分の方でちょこちょこ調整しようかなと。

PRの作り方は、そもそもmasterには何にも入ってないわけだし、パラレルで誰か作業しているわけではないので、究極master直突っ込みでもOKではあるんだけど、みやさまが差分管理のためにPR作るとかは自由で。

一方で、確かに将来CDI版のExampleも作るってなったら、ブランチを分けることになるだろうけど、現状見込みがないので、いったんGuice版がmasterでいいかなと。(CDIやることになったときにguiceブランチに引っ越しとか)

> どの程度まで作るべきか

画面を作るExampleは大変だと思うのでひとまずAPIに絞って...
理想的には harbor の:

o LidoProductListAction.java
https://github.com/lastaflute/lastaflute-example-harbor/blob/master/src/main/java/org/docksidestage/app/web/lido/product/LidoProductListAction.java

o LidoProductDetailAction.java
https://github.com/lastaflute/lastaflute-example-harbor/blob/master/src/main/java/org/docksidestage/app/web/lido/product/LidoProductDetailAction.java

o LidoAuthAction.java
https://github.com/lastaflute/lastaflute-example-harbor/blob/master/src/main/java/org/docksidestage/app/web/lido/auth/LidoAuthAction.java

ができると、他のフレームワークと比較しやすくなるので、目指したいところではある。
「ページング検索、一件検索、更新、メール」の基本要素が入るというところで。

**Comment by jflute** [comment]
(example-applicationブランチをEclipseでimportしてbuilding now)

(DBFluteBehaviorProducerの自動生成はDBFluteの機能として組み込んじゃってもいいのかも？)

**Comment by miyasama** [comment]
@jflute 
> 4つのプルリクマージする時は4-3-2-1の順番でいいのかな？
その順番で合っています！

PR・ブランチの運用について了解です。
3のPRが本題なので、Quarkus＋DBFlute使いたい方向けに差分分かりやすくしようかと思い、
PR分けてみただけなので、上記順でmasterまでマージする感じで大丈夫かと思います。

> ができると、他のフレームワークと比較しやすくなるので、目指したいところではある。
>「ページング検索、一件検索、更新、メール」の基本要素が入るというところで。

了解です。では、そのあたりまた数日かかると思いますが、追加しようかと思います。

ただ、メールや認証周りついてはLataFluteではないので、
完全にQuarkusの機能になってしまう＆使う人によって選ぶライブラリが違うので、一旦スキップしようかと思います。


ひとまず、いまの４つのPRを問題なければマージしてしまおうかと思うのですが大丈夫でしょうか？

**Comment by jflute** [comment]
@miyasama ありがとうー。ちょっとずつで大丈夫なので無理せず、でも助かるよー。
自分がQuarkusが全然馴染んでないもので...（＞＜

> ただ、メールや認証周りついてはLataFluteではないので、
> 完全にQuarkusの機能になってしまう＆使う人によって選ぶライブラリが違うので、一旦スキップしようかと思います。

なるほど、したら認証する部分やsendメソッドは空っぽとかでOK。

> ひとまず、いまの４つのPRを問題なければマージしてしまおうかと思うのですが大丈夫でしょうか？

OK

**Comment by miyasama** [comment]
@jflute 
了解です！では、マージしちゃいます！

**Comment by miyasama** [comment]
@jflute 
遅くなってしまったのですが、以下のPRでサンプルAPIを追加しました。
https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/12

以下の２つのAPI相当のものを追加しています。

> o LidoProductListAction.java
> https://github.com/lastaflute/lastaflute-example-harbor/blob/master/src/main/java/org/docksidestage/app/web/lido/product/LidoProductListAction.java
> 
> o LidoProductDetailAction.java
> https://github.com/lastaflute/lastaflute-example-harbor/blob/master/src/main/java/org/docksidestage/app/web/lido/product/LidoProductDetailAction.java

問題なさそうでしたら、マージしようかと思いますので、よろしくお願いします。

**Comment by jflute** [comment]
@miyasama ありがとうーーーー。あとで見させてもらうね。すごい。

**Comment by miyasama** [comment]
@jflute 
追加で、ログイン用APIと、マイページのAPIを追加しました。
別PRにしていますので、よろしくお願いします。

https://github.com/dbflute-example/dbflute-example-on-quarkus/pull/13

**Comment by jflute** [comment]
@miyasama それぞれレビューコメント入れておいたー

**Comment by miyasama** [comment]
@jflute 
ありがとうございます！
それぞれコメントと修正を入れました。

**Comment by miyasama** [comment]
@jflute 
レビューありがとうございますー
２つともPRマージしました。

exampleとしては、当初目標までは一旦完成かなと思いますので、
こちらのIssueはクローズします💡

**Comment by jflute** [comment]
@miyasama おおーー、ありがとう！大感謝感謝。

そのうち、ぼくの方でコメントを追記したりとか整理整頓やっていきたいなと思っているので、
そのときはフォローをぜひお願い。(せっかくなのでQuarkusもちょっと勉強しようかなと)

**Comment by miyasama** [comment]
@jflute 
ぜひぜひ、よろしくお願いしますー！
